### ISSUE TITLE
qlconfig.yml repository format issue

### ISSUE THREAD

**Issue by kjcolley7** [github/codeql-cli-binaries#92]
The experimental & undocumented `qlconfig.yml` format has a design flaw that I wanted to point out before it gets more widely available. The format allows you to add multiple separate registries along with a filter of which package name patterns are provided by it, which is wonderful. However, the `registryKind` key is at the top-level of the config file, rather than being attached to each repository. This means that you can't mix and match kinds of registries, like have one private NPM registry in addition to the public Docker registry from ghcr.io. Current format:

```yaml
registries:
  - url: <my private docker registry url>
    packages:
      - **
  - url: <another registry url here>
    packages:
      - **
registryKind: docker
credentials:
  "<my private docker registry url>":
    token: <redacted authentication token>
  "<another registry url here>":
    token: <redacted authentication token>
```

Suggested format:

```yaml
registries:
  - url: https://ghcr.io/v2/
    registryKind: docker
    packages:
      - codeql/**
  - url: <my private docker registry url>
    registryKind: docker
    packages:
      - **
  - url: <my internal NPM registry url>
    registryKind: npm
    packages:
      - **
  - url: file://path/to/local/cache
    regsitryKind: fs
    packages:
      - **
credentials:
  "<my private docker registry url>":
    token: <redacted authentication token>
  "<my internal NPM registry url>":
    token: <redacted authentication token>
```
